language: haxe
haxe: "4.0.5"
hxml:
  - unittests.hxml
  - package.hxml
  - doc.hxml

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install java 8.0.232.j9-adpt

before_script:
  - mkdir -p _build/java
  - git clone https://github.com/JaviCerveraIngram/connect-java-sdk.git _build/java
  - git remote rm origin
  - git remote add origin https://JaviCerveraIngram:${doc_token}@github.com/JaviCerveraIngram/connect-java-sdk.git
  - git remote -v
  - cp stuff/gitignore_java _build/java/.gitignore

after_script:
  - cd _build/java
  - git add .
  - git commit -m "Auto commit"
  - git push origin master
  - cd ../..

deploy:
  provider: pages
  local_dir: doc
  github_token: $doc_token
  skip_cleanup: true
  keep_history: false
  on:
    branch: master
