language: haxe
haxe: 4.0.5
hxml:
  - unittests.hxml
  - package.hxml
  - doc.hxml

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install java 8.0.232.j9-adpt
  - sudo apt install mono-devel -y

before_script:
  - "./stuff/java_clone.sh"

after_script:
  - "./stuff/java_commit.sh"

deploy:
  provider: pages
  local_dir: doc
  github_token: "$doc_token"
  skip_cleanup: true
  keep_history: false
  on:
    branch: CUSDK-55-csharp

after_deploy:
# Deploy to NuGet Gallery
  - sudo apt install nuget -y
  - cd _build/cs/bin
  - nuget pack Connect.nuspec
  - nuget push ConnectSDK.18.0.0.nupkg $nuget_token -source http://packages.nuget.org/v1/
  - cd ../../..
# Deploy to Maven Central
  - openssl aes-256-cbc -K $encrypted_6c315054a92d_key -iv $encrypted_6c315054a92d_iv -in stuff/key.gpg.enc -out stuff/key.gpg -d
  - gpg --batch --passphrase ${mvn_passphrase} --import stuff/key.gpg
  - rm stuff/key.gpg
  - python3 stuff/deploy_maven_central.py
# Deploy to PyPI
  - "./stuff/deploy_pypi.sh"
