language: haxe
haxe: 4.0.5
hxml:
  - unittests.hxml
  - package.hxml
  - doc.hxml

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install java 8.0.232.j9-adpt
  - sdk install maven 3.6.3
  - cp stuff/settings.xml ~/.m2/settings.xml
  - sed -i "s/__USER__/${mvn_user}/g" ~/.m2/settings.xml
  - sed -i "s/__PASSWORD__/${mvn_password}/g" ~/.m2/settings.xml
  - sed -i "s/__PASSPHRASE__/${mvn_passphrase}/g" ~/.m2/settings.xml
  - sed -i "s/__KEYNAME__/${mvn_keyname}/g" ~/.m2/settings.xml

before_script:
  - "./stuff/before_script.sh"

after_script:
  - "./stuff/after_script.sh"

deploy:
  provider: pages
  local_dir: doc
  github_token: "$doc_token"
  skip_cleanup: true
  keep_history: false
  on:
    branch: CUSDK-48-maven-deployment

after_deploy:
  - echo "-----BEGIN PGP PRIVATE KEY BLOCK-----" > key.gpg
  - echo "${mvn_key}" >> key.gpg
  - echo "-----END PGP PRIVATE KEY BLOCK-----" >> key.gpg
  - cat key.gpg
  - gpg --import key.gpg
  - rm key.gpg
  - gpg --list-secret-keys
  - mvn -X gpg:sign-and-deploy-file -DpomFile=stuff/pom.xml -Dfile=_build/java/Packager.jar
    -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ -DrepositoryId=nexus
