language: haxe
haxe: 4.0.5
hxml:
  - unittests.hxml
  - package.hxml
  - doc.hxml

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install java 8.0.232.j9-adpt
  - sdk install maven 3.6.3
  #- sdk install gradle 6.1

before_script:
  - "./stuff/java_clone.sh"

after_script:
  - "./stuff/java_commit.sh"

deploy:
  provider: pages
  local_dir: doc
  github_token: "$doc_token"
  skip_cleanup: true
  keep_history: false
  on:
    branch: CUSDK-48-maven-deployment

after_deploy:
# Deploy to Maven Central
  #- openssl aes-256-cbc -K $encrypted_6c315054a92d_key -iv $encrypted_6c315054a92d_iv -in stuff/key.gpg.enc -out stuff/key.gpg -d
  - openssl aes-256-cbc -K $encrypted_4ac79ed20675_key -iv $encrypted_4ac79ed20675_iv -in stuff/key.gpg.enc -out stuff/key.gpg -d
  - gpg --batch --passphrase ${mvn_passphrase} --import stuff/key.gpg
  - rm stuff/key.gpg
  - python3 stuff/deploy_maven_central.py
  #- "./stuff/maven_deploy.sh"
# Deploy to PyPI
  #- "./stuff/pypi_deploy.sh"
