language: haxe
haxe: 4.0.5
hxml:
  - unittests.hxml
  - package.hxml
  - doc.hxml

before_install:
  - export sdk_version=$(cat VERSION)
  - echo "SDK Version is $sdk_version."
  - curl -s "https://get.sdkman.io" | bash
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install java 8.0.232.j9-adpt
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo apt install apt-transport-https ca-certificates -y
  - echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - sudo apt update
  - sudo apt install mono-devel -y

before_script:
  - "./stuff/java_clone.sh"

after_script:
  - "./stuff/java_commit.sh"

deploy:
  provider: pages
  local_dir: doc
  github_token: "$doc_token"
  skip_cleanup: true
  keep_history: false
  on:
    branch: CUSDK-55-csharp

after_deploy:
# Deploy to NuGet Gallery
  - echo "*** Deploying to NuGet Gallery..."
  - sudo apt install nuget -y
  - cd _build/cs/bin
  - nuget pack Connect.nuspec
  - nuget push Connect.SDK.18.0.0.nupkg $nuget_token -source https://api.nuget.org/v3/index.json
  - cd ../../..
# Deploy to Maven Central
  - echo "*** Deploying to Maven Central..."
  - openssl aes-256-cbc -K $encrypted_6c315054a92d_key -iv $encrypted_6c315054a92d_iv -in stuff/key.gpg.enc -out stuff/key.gpg -d
  - gpg --batch --passphrase ${mvn_passphrase} --import stuff/key.gpg
  - rm stuff/key.gpg
  - python3 stuff/deploy_maven_central.py
# Deploy to PyPI
  - echo "*** Deploying to PyPI..."
  - sudo apt install python3-pip -y
  - sudo -H pip3 install --upgrade pip
  - sudo -H pip3 install wheel
  - sudo -H pip3 install twine
  - cd _build/python
  - python3 setup.py sdist bdist_wheel
  - twine upload -u __token__ -p $pypi_token dist/*
  - cd ../..
